### ISSUE TITLE
questions about "ImportError: No module named intervaltree"

### ISSUE THREAD

**Issue by sunqinxuan** [shichaoy/pop_up_slam#21]
Hi,

I've successfully built the code and run the following line for a test.

`roslaunch pop_planar_slam pop_planar_tum_far_example.launch`

Then I got the error here.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jason/SqX/popup_ws/devel/lib/python2.7/dist-packages/pop_up_python/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/home/jason/SqX/popup_ws/src/pop_up_slam/pop_up_python/python/pop_up_python/pop_up_fun.py", line 7, in <module>
    from intervaltree import Interval, IntervalTree  # to select not overlapping edges
ImportError: No module named intervaltree
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pop_up_fun' is not defined
```

I'm sure I've installed "intervaltree". But when I test it in python, it does not work and outputs the same ImportError. 
I wonder if anyone has an idea what else I can do to make it work properly.

Thanks very much for helping.

cheers, 
Elinor

**Comment by szx1995** [comment]
pip install intervaltree
